name: Node.js CICD GreenFeast

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Determine changed services
        id: changed_services
        run: |
          echo "Changed services:"
          CHANGED_SERVICES=""
          SERVICES=("api-gateway" "api-gateway-mobile" "management-service" "notification-service" "order-service" "payment-service" "recommend-service" "statistics-service" "tms-service" "
          order-service-2" "frontend")
          for service in "${SERVICES[@]}"; do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "$service/"; then
              CHANGED_SERVICES="$service $CHANGED_SERVICES"
            fi
          done
          echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV
      
      - run: export NODE_OPTIONS="--max_old_space_size=4096"
      
      - name: Build and run changed services
        run: |
          if [ -z "${{ env.CHANGED_SERVICES }}" ]; then
            echo "No services changed. Skipping build."
          else
            for service in ${{ env.CHANGED_SERVICES }}; do
              echo "Building and running $service..."
              docker compose -p greenfeast up -d --build $service
            done
          fi